### ISSUE TITLE
!creative not working

### ISSUE THREAD

**Issue by Jimbodiah** [mircearoata/SatisfactoryPakUtilityMod#1]
It seems the cost for building structures is still active, despite using !creative. 

NB: I can get all the other functions to work.

**Comment by Jimbodiah** [comment]
I just notices I have Kmod installed and I think it is interfering. When I enable no-cost there, it does work.

**Comment by mircearoata** [comment]
It is possible that they are interfering, if Kronos Mod is constantly setting the state of nocost. Probably same goes for nopower. KMod is closed source so if I want to know how it handles those, I'll have to ask Kronos

**Comment by Jimbodiah** [comment]
I can get it to work through kronos, probably more an issue on his end if he keeps overwriting that parameter.
