### ISSUE TITLE
when client disconnects, game crashes

### ISSUE THREAD

**Issue by bghira** [mircearoata/SatisfactoryPakUtilityMod#11]
the flying component of this mod is causing crashes in MP.

if a client purpostly/unintentionally disconnects or crashes, the host then crashes.

**Comment by fanatictentacle** [comment]
I have the same problem, also it seems as if someone is flying and another player wants to join this leads to problems as well.

**Comment by Sonic4080** [comment]
> 
> 
> I have the same problem, also it seems as if someone is flying and another player wants to join this leads to problems as well.

I can confirm, if someone joins a session while the Host is flying the game crashes for the Host, and sometimes but not always for the client as well.

**Comment by mircearoata** [comment]
Does this still happen after the latest update?
