### ISSUE TITLE
Item List

### ISSUE THREAD

**Issue by fanatictentacle** [mircearoata/SatisfactoryPakUtilityMod#12]
Sorry if this is stupid, but where the heck is a list of the items for the give command?

**Comment by mircearoata** [comment]
You have to type the name of the item exactly as you see it ingame, in the language your game is, spaces and everything included

**Comment by maiconpll** [comment]
friends,

I'm doing exactly that, in the language of Brazil (Portuguese).

Example:
!give barra de ferro 100
!give barra_de_ferro 100
!give barra_de_ferro_C 100
!give barradeferro 100
!give barradeferro_C 100

None of these options are working.
