### ISSUE TITLE
Mod stopped worked working after a update

### ISSUE THREAD

**Issue by tuanhphung** [mircearoata/SatisfactoryPakUtilityMod#14]
Game wont load the mod properly after a update (version CL150216)

**Comment by Merkury90** [comment]
Yeah, can confirm that mod is no longer working.
After reinstalling SMM it is inpossible to even add to anymore.

Any chance for an update?

**Comment by ZoeFken** [comment]
Any update if the mod will be updated for satisfactory update 4?

**Comment by barbrady123** [comment]
It looks like it's been updated!!!!!

**Comment by auddie2015** [comment]
The commands enter but do not enable. !fly is accepted as a command but it does not return "Enabled Fly Mode"

The game is autoupdated so it's always the latest version. SML is current (2.2.1) and I have 0.5.0 of this mod installed.

**Comment by AzzA-187** [comment]
I have the same issue as auddie2015 except i dont seem to get the "!pak loaded" message when the game first starts. 
SMM is current (2.2.1) and 0.5.0 of this mod installed.

**Comment by AzzA-187** [comment]
I've changed the development profile from 'modded' (SML v2.2.1) to 'development' (now running as SML v3.0.0) and the mod is now working in game. 
Hope that helps ya'll.
