### ISSUE TITLE
Teleport

### ISSUE THREAD

**Issue by L3Chuuck** [mircearoata/SatisfactoryPakUtilityMod#15]
The teleport command is not working, after i have saved a location it says that there is no name with that teleport.

**Comment by Asaurus7** [comment]
Favorite mod in satisfactory. Worked great in Update3

!tp save b1
"Saved your current location as b1"

!tp b1
" Could not find teleport location b1"

!tp delete b1
Deleted teleport b1

I've tried this with multiple names (upper/lower case, numbers, long/short) no luck

**Comment by mircearoata** [comment]
Fixed this in v0.5.1
