### ISSUE TITLE
Game crashes with this mod at irregular intervals. 

### ISSUE THREAD

**Issue by mistermert504** [mircearoata/SatisfactoryPakUtilityMod#17]
Dear Developer, 

Unfortunately SATIS keeps crashing since I started using the Magic Machines mod. Can you tell me if it is really due to your mod? I have attached the crash report. 

I play the Early Access CL 151248 - SML 3.0.0

I also use the following mods:

Pak Utility Mod, All Nodes Pure, Smart!

Thanks a lot

`Version: 151248, IsEditor: No, IsPerforceBuild: No, BuildConfiguration: Shipping, Launcher: Epic, NetMode: Standalone, IsUsingMods: Yes

Assertion failed: mOuterBuildable [File:D:/ws/SB-160502110050-fad/UE4/Games/FactoryGame/Source/FactoryGame/Private/FGFactoryConnectionComponent.cpp] [Line: 241]

UE4_Core_Win64_Shipping!AssertFailedImplV() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\core\private\misc\assertionmacros.cpp:100]
UE4_Core_Win64_Shipping!FDebug::CheckVerifyFailedImpl() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\core\private\misc\assertionmacros.cpp:450]
UE4_FactoryGame_Win64_Shipping!UFGFactoryConnectionComponent::Factory_GrabOutput() [d:\ws\sb-160502110050-fad\ue4\games\factorygame\source\factorygame\private\fgfactoryconnectioncomponent.cpp:241]
UE4_FactoryGame_Win64_Shipping!UFGFactoryConnectionComponent::execFactory_GrabOutput() [d:\ws\sb-160502110050-fad\ue4\games\factorygame\intermediate\build\win64\ue4\inc\factorygame\fgfactoryconnectioncomponent.gen.cpp:183]
UE4_CoreUObject_Win64_Shipping!UFunction::Invoke() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\coreuobject\private\uobject\class.cpp:5543]
UE4_CoreUObject_Win64_Shipping!UObject::CallFunction() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\coreuobject\private\uobject\scriptcore.cpp:929]
UE4_CoreUObject_Win64_Shipping!UObject::ProcessContextOpcode() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\coreuobject\private\uobject\scriptcore.cpp:2796]
UE4_CoreUObject_Win64_Shipping!UObject::execLetBool() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\coreuobject\private\uobject\scriptcore.cpp:2697]
UE4_CoreUObject_Win64_Shipping!ProcessLocalScriptFunction() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\coreuobject\private\uobject\scriptcore.cpp:997]
UE4_CoreUObject_Win64_Shipping!ProcessScriptFunction<void (__cdecl*)(UObject *,FFrame &,void *)>() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\coreuobject\private\uobject\scriptcore.cpp:828]
UE4_CoreUObject_Win64_Shipping!UObject::execLocalFinalFunction() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\coreuobject\private\uobject\scriptcore.cpp:2923]
UE4_CoreUObject_Win64_Shipping!ProcessLocalScriptFunction() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\coreuobject\private\uobject\scriptcore.cpp:997]
UE4_CoreUObject_Win64_Shipping!UObject::ProcessInternal() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\coreuobject\private\uobject\scriptcore.cpp:1087]
UE4_CoreUObject_Win64_Shipping!UFunction::Invoke() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\coreuobject\private\uobject\class.cpp:5543]
UE4_CoreUObject_Win64_Shipping!UObject::ProcessEvent() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\coreuobject\private\uobject\scriptcore.cpp:1916]
UE4_Engine_Win64_Shipping!AActor::ProcessEvent() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\engine\private\actor.cpp:851]
UE4_Engine_Win64_Shipping!AActor::BeginPlay() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\engine\private\actor.cpp:3529]
UE4_FactoryGame_Win64_Shipping!AFGBuildable::BeginPlay() [d:\ws\sb-160502110050-fad\ue4\games\factorygame\source\factorygame\private\buildables\fgbuildable.cpp:200]
UE4_FactoryGame_Win64_Shipping!AFGBuildableFactory::BeginPlay() [d:\ws\sb-160502110050-fad\ue4\games\factorygame\source\factorygame\private\buildables\fgbuildablefactory.cpp:183]
UE4_FactoryGame_Win64_Shipping!AFGBuildablePipeReservoir::BeginPlay() [d:\ws\sb-160502110050-fad\ue4\games\factorygame\source\factorygame\private\buildables\fgbuildablepipereservoir.cpp:73]
UE4_Engine_Win64_Shipping!AActor::DispatchBeginPlay() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\engine\private\actor.cpp:3449]
UE4_Engine_Win64_Shipping!AWorldSettings::NotifyBeginPlay() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\engine\private\worldsettings.cpp:246]
UE4_FactoryGame_Win64_Shipping!AFGWorldSettings::NotifyBeginPlay() [d:\ws\sb-160502110050-fad\ue4\games\factorygame\source\factorygame\private\fgworldsettings.cpp:228]
UE4_Engine_Win64_Shipping!AGameMode::HandleMatchHasStarted() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\engine\private\gamemode.cpp:239]
UE4_Engine_Win64_Shipping!AGameMode::SetMatchState() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\engine\private\gamemode.cpp:355]
UE4_Engine_Win64_Shipping!UWorld::BeginPlay() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\engine\private\world.cpp:4243]
UE4_Engine_Win64_Shipping!UEngine::LoadMap() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\engine\private\unrealengine.cpp:13023]
UE4_FactoryGame_Win64_Shipping!UFGGameEngine::LoadMap() [d:\ws\sb-160502110050-fad\ue4\games\factorygame\source\factorygame\private\fggameengine.cpp:29]
UE4_Engine_Win64_Shipping!UEngine::Browse() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\engine\private\unrealengine.cpp:12228]
UE4_Engine_Win64_Shipping!UEngine::TickWorldTravel() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\engine\private\unrealengine.cpp:12426]
UE4_Engine_Win64_Shipping!UGameEngine::Tick() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\engine\private\gameengine.cpp:1686]
UE4_FactoryGame_Win64_Shipping!UFGGameEngine::Tick() [d:\ws\sb-160502110050-fad\ue4\games\factorygame\source\factorygame\private\fggameengine.cpp:13]
UE4_Win64_Shipping!FEngineLoop::Tick() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\launch\private\launchengineloop.cpp:4910]
UE4_Win64_Shipping!GuardedMain() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\launch\private\launch.cpp:169]
UE4_Win64_Shipping!GuardedMainWrapper() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\launch\private\windows\launchwindows.cpp:137]
UE4_Win64_Shipping!WinMain() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\launch\private\windows\launchwindows.cpp:268]
UE4_Win64_Shipping!__scrt_common_main_seh() [d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288]
kernel32
ntdll`

**Comment by mircearoata** [comment]
This crash is caused by Magic Machine, the fluid spawner
