### ISSUE TITLE
Combine "!fly fast" and "!fly medium"?

### ISSUE THREAD

**Issue by pnieuwkamp** [mircearoata/SatisfactoryPakUtilityMod#18]
Hi, I love this mod, especially flying. However, I find that I'm constantly switching between medium and fast flight. Medium is perfect when I'm building stuff, but quite tedious when I want to go to satellite factories, while fast is perfect for zooming around the map, but way too fast inside my base.

It's gotten to the point where I'm contemplating installing a macro tool to type "(enter)!fly medium(enter)" and "(enter)!fly fast(enter)" for me...

Would it be possible to add a mode where the non-sprint speed is that of (non-sprint) medium, and the sprint speed is that of the (sprint) fast?

**Comment by edburgos** [comment]
A `!fly <number>`  might be a great idea so we can customize the fly speed at our own liking.  <number> could be a setting between 1.00-100.00 or whatever makes sense, bonus point if we get to save it as a setting.

**Comment by mircearoata** [comment]
Version 0.6.0 adds customizable speeds and speed names.

**Comment by Strome76** [comment]
I like the customizable speeds. Great implementation.
But I don't want to seem ungrateful when a say that this request is is not really completed. I think [pnieuwkamp ](https://github.com/pnieuwkamp) requests a changed speed ratio between walking/sprinting. 
May I suggest that you add a multiplier to each speed setting in the customize menu? If having different ratios is possible.

**Comment by mircearoata** [comment]
Thanks! Added that in v0.7.0

**Comment by Strome76** [comment]
This new feature is great. I'm really happy about it.

The new menu makes it easy to create your own speeds. Great implementation from the requests. 

Thanks for the great work. [mircearoata](https://github.com/mircearoata)!
It wasn't until you made it I new I needed it. Now I don't need to change speeds as often. :)

And thanks for the ideas, [pnieuwkamp](https://github.com/pnieuwkamp) / [edburgos](https://github.com/edburgos)
