### ISSUE TITLE
Control Bindings

### ISSUE THREAD

**Issue by th3fallen** [mircearoata/SatisfactoryPakUtilityMod#2]
Is there a way that im missing to edit the control bindings for flight mode, the ctrl to go down is interfering with the mass dismantle in experimental.

**Comment by mircearoata** [comment]
Currently there is no way for the user to change the bindings.

**Comment by eyeonus** [comment]
I would like to request putting that up high on the priority list please, as the alt to go down being used now interferes with the hot bar scrolling. Even if it means editing a text file in the config file, I'm fine with not being able to change it in game.

**Comment by Forbidden-Duck** [comment]
Pressing CTRL for me doesn't even go down when flying. I have to turn fly off just to go down

**Comment by ForsakenSwit** [comment]
This needs to be set to C (Crouch). This key would be more intuitive for users and wouldn't interfere with other game commands. CTRL or ALT interferes with default keybindings making it difficult to build while flying.

**Comment by ovitente** [comment]
I totally agree with previous comments, I am ready to search for solutions even through editing sources of the mod.

**Comment by mircearoata** [comment]
The fly down key is now the crouch key, whatever you have that bound to
