### ISSUE TITLE
!God causing game to lock up

### ISSUE THREAD

**Issue by ZezaReignhalt** [mircearoata/SatisfactoryPakUtilityMod#27]
using !god causes the game to freeze up on existing save files.  This is for 188609.823
[DxDiag.txt](https://github.com/mircearoata/SatisfactoryPakUtilityMod/files/9186922/DxDiag.txt)
.

**Comment by foreachthing** [comment]
Same here.
Latest version: 0.6.0
Satisfactory: 4.26.2.0 (Update 5)
[DxDiag.txt](https://github.com/mircearoata/SatisfactoryPakUtilityMod/files/9203258/DxDiag.txt)

**Comment by mircearoata** [comment]
See #26
