### ISSUE TITLE
Not working in latest 2 Experimental builds  v0.3.4.0 - Build 119583 and v0.3.4.1 - Build 119646

### ISSUE THREAD

**Issue by Wizard17** [mircearoata/SatisfactoryPakUtilityMod#6]
This mod has always been a "must have" for me because of flightmode. Sadly, my Epic launcher decided to update Experimental (which it has been doing a few times already). In previous build, I then happened to find this mod not working at all anymore. I had hope it got fixed in the latest quick patch that followed, but sadly no. The mod gets loaded, in Chat /info shows it loaded and ready, but anything you type starting with ! doesn't do anything anymore. Perhaps the devs confiscated the ! as first character for something else in chat, rendering this Mod inaccessable ?

**Comment by mircearoata** [comment]
I already found the issue, and it is SML fails to load the mod in existing saves, because it is compiled for an older version of the game. The update for SML is almost ready, and with this update Pak UtilityMod will also have an update bringing multiplayer compatibility

**Comment by Wizard17** [comment]
After manual update (See SatisfactorModLauncher-issues) I started the experimental game, which now is v0.3.4.2 - Build 119805, Pak UtilityMOD worked once. I've been enjoying it again until I eccidentally flew of the map, and died. Reloading the same save, the Mod didn't work anymore as before. Also, loading other saves, not working. Quiting the game, removing the Mod, re-installing the Mod starting the game with same save again, not working... It's weird to me though that it worked once right after the ModLauncher update and not anymore since ?

**Comment by mircearoata** [comment]
SML randomly fails to load mods in experimental. New version coming soon

**Comment by Wizard17** [comment]
Well, just for your info. I'm having both Experimental and Retail update 3 installed. I always have 4 mods active on both:
ProgrammableElevatorMod v2.1.0 (there's an update for right now)
UtilityMod
UtilitySigns
and Holes
All Mods always load, regardless retail or experimental. It is only UtilityMod that started "failing" since mentioned experimental-version. All others continue to work starting game or reloading a save.
I know of one other Mod which I gave up on anyways, that's the Light it Up Mod, that too started failing and even crashed Experimental since v0.3.4.0, so I just disabled it and forgot about it...
I tried to use retail, but then ofcourse I can't load my save (just hangs) so would have to start building from scratch. Considering the shear size and complexity of what I'm trying to build I very much don't feel much to start over from nothing :-)
Hope this info might help somehow...
If you'd like me to be alpha-tester or anything I can do to help, I'm all ears. I'm sadly just no use when it comes to programming, but early testing or otherwise might help perhaps :-)

**Comment by mircearoata** [comment]
SML failed to spawn InitMod, which Pak UtilityMod relies on to add the chat listener. For other mods with schematic, if the schematic was already unlocked, the game knew it has to load it and the buildings and everything.
SML has been updated and works now on experimental
